<!DOCTYPE html>
<html>

<?php

const TITLE = SITE_NAME . ' - Registration';

Globals::AskTemplatePart('head');
?>

<body>

<?php
    Globals::AskTemplatePart('header');
    Globals::AskTemplatePart('navigation');
?>

<section>
    <h2>Registration</h2>
    <form>
        <input type="text" name="login" placeholder="login">
        <br>
        <input type="password" name="password" placeholder="password">
        <br>
        <input type="submit">
    </form>
</section>
</body>

</html>
