<!DOCTYPE html>
<html>

<?php

const TITLE = SITE_NAME . ' - Registration';

Globals::AskTemplatePart('head');
Globals::AskTemplatePart('navigation');
?>

<body>
    <h2>REGISTRATION</h2>
    <form>
        <input type="text" name="login" placeholder="login">
        <br>
        <input type="password" name="password" placeholder="password">
        <br>
        <input type="submit">
    </form>

</body>

</html>
